### ISSUE TITLE
Temperature Units

### ISSUE THREAD

**Issue by ghost** [rootasjey/Feels#2]
Great work! However, I'm not sure if the unit selection switch in the app settings is not functioning correctly or hasn't been implemented yet. In the US, we use Fahrenheit and the app is only displaying in Celsius.

**Comment by synthetrash** [comment]
I noticed that too. So it's not working yet.
// nvm it works on the current branch, so just not released to the store version yet

**Comment by rootasjey** [comment]
Hello,
Thank you for your comments.

As @synthetrash mentionned, I've already fixed this issue and I'll release it to the store on Sunday.
So you should receive the update during next week.

**Comment by rootasjey** [comment]
The update is now live in the Store, so I close this issue.
